### ISSUE TITLE
Bug: `TypeError: dest.on is not a function` when including this pipeline in another gulp plugin

### ISSUE THREAD

**Issue by franciov** [kenzanlabs/pipeline-minify-js#12]
I got the following error when trying to include this pipeline in another gulp plugin:
```
     TypeError: dest.on is not a function
      at DestroyableTransform.Readable.pipe (node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:516:8)
      at Context.<anonymous> (specs/scripts.spec.js:22:8)
```
that happens running [the following test](https://github.com/ThomsonReuters-IPS/webui-pipeline-archive-dist/pull/2/files#diff-3fe3bc3692d724a136a0d14bea79c9e9R21):
```
    gulp.src(mockSrc)
      .pipe(distArchivePipeline.distributeScripts())
      .pipe(gulp.dest(mockDest));
```
where `distArchivePipeline.distributeScripts()` is implemented [in this way](https://github.com/ThomsonReuters-IPS/webui-pipeline-archive-dist/pull/2/files#diff-1fdf421c05c1140f6d71444ea2b27638R15):
```
  distributeScripts() {
    return lazypipe()
      .pipe(function() {
        let minifyOptions = {
          addSourceMaps: false
        };

        return jsMinifyPipeline(minifyOptions).minifyJS();
      });
  },
```

Any ideas?

**Comment by obuckley-kenzan** [comment]
@franciov 
Although unituitive, I wonder if the issue is related to the current usage expectations of this pipeline
https://github.com/kenzanlabs/pipeline-minify-js#usage

```javascript
var minifyPipeline = require('pipeline-minify-js')();  //note the need to call the pipeline as a function immediately
```

This is something we are looking to put on the roadmap to change
https://github.com/kenzanlabs/keystone/issues/7

And something we are doing with https://github.com/kenzanlabs/pipeline-validate-js/ as we refactor it up a little bit

**Comment by franciov** [comment]
@obuckley-kenzan Yes, the problem was related to this, thanks!

**Comment by obuckley-kenzan** [comment]
Paraphrased from an explanation by @paul-barry-kenzan 

This was an issue when using this pipeline with lazypipe.

`lazyPipe` actually returns a function that needs to be invoked. Because of this, the only way I can get the pipeline to work properly is to call the returned function, like so:

```javascript
return gulp.src(uiJsFiles)
    .pipe(distArchivePipeline.distributeScripts()()) // notice the double `()()`
    .pipe(gulp.dest('./dist/'));
```
We saw this same issue in the validate-js pipeline, and @cxoltero was able to resolve by first storing the lazyPipe stream, and then returning the invoked stream, like so:

```javascript
distributeScripts() {
    let stream = lazypipe()
      .pipe(function() {
        let minifyOptions = {
          addSourceMaps: false
        };

        return jsMinifyPipeline(minifyOptions).minifyJS();
      });

  return stream();

  }
```
Here's his example: 
https://github.com/cxoltero/pipeline-validate-js/blob/spec316/src/index.js#L91

**Comment by obuckley-kenzan** [comment]
this won't be an issue when this enhancement request goes through
https://github.com/kenzanlabs/keystone/issues/7
